### ISSUE TITLE
What are the requirements?

### ISSUE THREAD

**Issue by you213** [ajeetdsouza/pifs#3]
Do I need to have a specific C++ application installed? Do I need to use Linux?

**Comment by ajeetdsouza** [comment]
Hi @you213,

> Do I need to have a specific C++ application installed?

pifs uses the [cmake](https://cmake.org/) build tool, so you'll need to install that first. You will also need FUSE headers, which you can get by installing `libfuse3-dev` (Ubuntu) or `fuse3-devel` (Fedora). Once you have this (and a C++ compiler, of course) installed, you should be good to go!

> Do I need to use Linux?

I've only tested this on Linux systems, but I don't see why it shouldn't work on other systems supporting FUSE, as it uses nothing OS-specific.

---

I hope that answers your questions!
