### ISSUE TITLE
Doesn't even build lol

### ISSUE THREAD

**Issue by ShockedCoder** [ajeetdsouza/pifs#5]
![image](https://user-images.githubusercontent.com/40272709/209596470-34203dab-beaa-4e9a-896f-5e58ada20982.png)
👍

**Comment by yuppox** [comment]
@c4llv07e
It still didn't build with that fix. I got the same error.

**Comment by ajeetdsouza** [comment]
> Doesn't even build lol

Maintainers are not obligated to take time out of their day to help you. If you want help, learn to be polite.
